init.lua

Feature: Implemented a function that lets you create Line components from a given string with a customization according to the other parameters and added its documentation.

[FEAT] Function For Creating Components From String

---

init.lua

Feature: Implemented enumerations for various variables in components setup, and then documentation of the function that has a role in the component setup has been added.

[FEAT] Enumerations And Documentation For Component Setup

---

init.lua

Issue: In one function, component type values was not been set.
Fix: Added component type to this functions.

[FIX] Missing Component Type Added

---

init.lua

Feature: Duplicated code of string based components removed by getting
string values from function instead of Line values and then their
components created with create_components_from_str function. Also their
functions received documentation. Moreover, previous and following
component types are no longer needed to create a component.

[FEAT] String Based Components Refactored 

---

init.lua

Feature: Implemented an automatic creation and configuration system for
string based components for both header-line and status-line.

[FEAT] Automatic Configuration For String Based Components

---

init.lua

Feature: Implemented an automatic creation and configuration system for
line based components for both header-line and status-line. Moreover,
now create:tabs function can work in right side correctly.
Feature: A new type of components designed to provide multi-colorizable
components which also reduce the need for line based components.Moreover,
implemented automatic creation and configuration system for
multi-colorizable components for both header-line and status-line.

[FEAT] Automatic Configuration For Line Based Components AND [FEAT] Multi-Colorizable Components

---

README.md
init.lua

**Features:**
- Components divided to three types: string, coloreds and line.
- Automatic component configuration system implemented for all types.
- Custom component creation support.
- Most of the duplicated codes are taken care of.
- Documentation added.
Resolves: #1

[UPDATE] Automatic Configuration

---

init.lua

Feature: All empty components which may result of impossible request will be disabled. Moreover, in config_line an error checker for invalid function name implemented.

[FEAT] Disabling Empty Components

---

init.lua

Feature: Implemented other basic components for different user needs.

[FEAT] More Basic Components Implemented

---

README.md
init.lua

**Features:**
- Disabling empty components.
- 6 new components.

[UPDATE] More Components

---

README.md

Hello, 
It seems in the docs that there a missing parenthesis for the code to work. I just added them, please review ! 
Thanks,
Yushi

[FIX]: add missing parenthesis

---

init.lua

Feature: Background of both header-line or status-line can be removed. Moreover, functions's probably all of the optional paramaters indicated.

[FEAT] Configuration For Background Of Both Lines

---

init.lua

Feature: Separators styles now decided according to the new non-empty section.

[FEAT] More Advanced Separator Connection

---

init.lua

Feature: Header-line or status-line displayement became togglable.

[FEAT] Displayment of Header-line and Status-line

---

init.lua

**Features:** 
- Implemented a config parameter to whether or not use section-c style as background of both header-line and status-line.
- Implemented a config parameter to completely removing header-line and/or status-line.
- Separators style configuration improved.

[Update] Simplicity

---

init.lua

Feature: Added default variables for configuration values so that key-value pairs for all configuration variables are not needed to be added in config.

[FEAT] Default Values

---

init.lua

Feature: Implemented a way to easily add a theme.

[FEAT] Theme Import Support

---

init.lua

- Added default values for config parameters.
- Implemented a config parameter to get theme configuration.

[UPDATE] Customization

---

init.lua

Feature: Add-ons can be created in a similar way to the default components without needing custom paramters to be set to true.

[FEAT] Add-On Support For Components

---

init.lua

Feature: Add-ons for component types can be created in a similar way to the default component types.

[FEAT] Add-On Support For Component Types

---

init.lua

Feature: Duplicated code in the config_separator are refactored into a new function which configures the component's separators.

[FEAT] Components Configuration Refactored

---

README.md
init.lua

Issue: When config not provided, it crashes the Yazi.
Fix: Implemented an error checking for preventing configless
initialization from crashing Yazi.

[FIX] Configless Initialization

---

init.lua

details: With yazi's function, paths are shortened easily.

[FEAT] Shortened Paths

---

README.md
init.lua

**Features:**
- Yazi v0.3.0 support.
- Add-ons system implemented.
- Shortened paths for files and directories.
Resolves: #21

[UPDATE] Enlarged
